services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    numero2_contact_persons.listener.contact_person.contact_person_parse:
        class: numero2\ContactPersonsBundle\EventListener\ContactPerson\ContactPersonParseListener
        arguments:
            - '@contao.image.studio'
            - '@contao.routing.content_url_generator'
            - '@request_stack'
        tags:
            - { name: kernel.event_listener, event: contao.contact_person_parse, priority: 0 }


    numero2_contact_persons.listener.data_container.contact_person:
        class: numero2\ContactPersonsBundle\EventListener\DataContainer\ContactPersonListener